# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.10.2
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - bourdon.ugo@gmail.com
jdk:
  - openjdk7
